# -*- coding: utf-8 -*-
"""sample7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aiqkc9BULNjzWhPDx7Np-TJUiRWf9_ez
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# %matplotlib inline

muons = pd.read_csv('http://opendata.cern.ch/record/545/files/Dimuon_DoubleMu.csv')
muons.head()

len(muons)

fig = plt.figure(figsize=(15, 10))

plt.hist(muons.M, 300, range = (0,150))

plt.xlabel('Invariant mass (GeV/$c^2$)', fontsize = 15)
plt.ylabel('Number of events \n', fontsize = 15)
plt.title('Measured distribution of events with two muons \n', fontsize = 15)

plt.show()

bump = muons[(muons.M >= 80) & (muons.M <= 100)]

fig = plt.figure(figsize=(15, 10))

plt.hist(bump.M, 300, range = (80,100))

plt.xlabel('Invariant mass (GeV/$c^2$)', fontsize = 15)
plt.ylabel('Number of events \n', fontsize = 15)
plt.title('Measured distribution of events with two muons \n', fontsize = 15)

plt.show()

sample2 = pd.read_csv('https://goo.gl/sp8gYx')
sample2.head()

sample3 = pd.read_csv('https://goo.gl/g8y9TC')
sample3.head()

sample4 = pd.read_csv('https://goo.gl/MFNdBN')
sample4.head()

sample5 = pd.read_csv('https://goo.gl/GJGJ9m')
sample5.head()

sample6 = pd.read_csv('https://goo.gl/5kgxKF')
sample6.head()

sample7 = pd.read_csv('https://goo.gl/PU9w7m')
sample7.head()

invariant_mass = np.sqrt(2*sample7.pt1*sample7.pt2*(np.cosh(sample7.eta1-sample7.eta2) - np.cos(sample7.phi1-sample7.phi2)))

print(invariant_mass)

fig = plt.figure(figsize=(15, 10))


plt.hist(invariant_mass, bins=300, range=(0,130))

axes = plt.gca()
axes.set_ylim([0,350])


plt.xlabel('Invariant mass [GeV]')
plt.ylabel('Number of events')
plt.title('Histogram of invariant masses of two electrons\n')


selected = []

fig = plt.figure(figsize=(15, 10))

plt.hist(invariant_mass, 350, range = (80,100))

plt.xlabel('Invariant mass (GeV/$c^2$)', fontsize = 15)
plt.ylabel('Number of events \n', fontsize = 15)
plt.title('Measured distribution of events with two electrons \n', fontsize = 15)

plt.show()

sample8 = pd.read_csv('https://goo.gl/tTy5gr')
sample8.head()

